name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Ollama models
        uses: actions/cache@v3
        with:
          path: ~/.ollama/models # Adjust to actual Ollama model path
          key: ${{ runner.os }}-ollama-models
          restore-keys: |
            ${{ runner.os }}-ollama-models

      - name: Install dependencies
        run: npm install

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull llama3.2 model
        run: ollama pull llama3.2

      - name: Check version Ollama
        run: ollama -v

      - name: Run unit tests
        run: npm run test
